### ISSUE TITLE
Unnecessary bundling

### ISSUE THREAD

**Issue by cprecioso** [ractivejs/rcu#24]
`rcu` is making `npm` grab `eval2`, `tippex` and `vlq`, but they aren't actually used, because `rollup` is set up to bundle them into the `dist/` packages. So, either these `dependencies` should be moved to `devDependencies`, or `rollup-plugin-node-resolve` shouldn't be used any more.

**Comment by Rich-Harris** [comment]
Good catch, thanks! Released a new version that moves them to devDependencies
